/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageInterface extends Interface {
  getFunction(
    nameOrSignature: "currentMessage" | "setMessage"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "currentMessage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setMessage", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "currentMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMessage", data: BytesLike): Result;
}

export namespace MessageUpdatedEvent {
  export type InputTuple = [oldMessage: string, newMessage: string];
  export type OutputTuple = [oldMessage: string, newMessage: string];
  export interface OutputObject {
    oldMessage: string;
    newMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Message extends BaseContract {
  connect(runner?: ContractRunner | null): Message;
  waitForDeployment(): Promise<this>;

  interface: MessageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentMessage: TypedContractMethod<[], [string], "view">;

  setMessage: TypedContractMethod<[_message: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentMessage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMessage"
  ): TypedContractMethod<[_message: string], [void], "nonpayable">;

  getEvent(
    key: "MessageUpdated"
  ): TypedContractEvent<
    MessageUpdatedEvent.InputTuple,
    MessageUpdatedEvent.OutputTuple,
    MessageUpdatedEvent.OutputObject
  >;

  filters: {
    "MessageUpdated(string,string)": TypedContractEvent<
      MessageUpdatedEvent.InputTuple,
      MessageUpdatedEvent.OutputTuple,
      MessageUpdatedEvent.OutputObject
    >;
    MessageUpdated: TypedContractEvent<
      MessageUpdatedEvent.InputTuple,
      MessageUpdatedEvent.OutputTuple,
      MessageUpdatedEvent.OutputObject
    >;
  };
}
